### ISSUE TITLE
Install instructions for gx

### ISSUE THREAD

**Issue by VictorBjelkholm** [whyrusleeping/iptb#29]
Recently tried iptb out, once I got it working it was working fine.

However, installation of the dependencies seems a bit wonky. I tried to use gx and just did `gx install` after cloning the repository inside my GOPATH but I still got errors for dependencies missing.

**Comment by Kubuxu** [comment]
Did you install `gx-go` too?

**Comment by VictorBjelkholm** [comment]
@Kubuxu yeah, my setup is correct afaik, go-ipfs and other things I can install without problems, this is the first time this happens.

**Comment by whyrusleeping** [comment]
@VictorBjelkholm Yeah, it needs a few things from go-ipfs, and we don't import go-ipfs as a package yet. We should work on fixing this soon

**Comment by VictorBjelkholm** [comment]
This seems to be working now. Both via `go get` and doing `gx install`
